name: dkppc-min
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        cd wii
        make -f Makefile-tc.wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: threaded-code
        path: |
          ./wii/*.dol
